### PR TITLE
Add citation file

### PR DESCRIPTION
**Pull request by regislon**
# Describe your changes

Add citation file

# Related GitHub issues and pull requests

- Ref: #13

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] Don't forget to link PR to issue if you are solving one.

### CODE REVIEW

**Comment by guilbep** [comment]
Perfect @regislon Maybe we should add a description in the README.md file. What do you think ?

**Review by guilbep — APPROVED** [review]

**Comment by regislon** [comment]
>

**Comment by regislon** [comment]
> Perfect @regislon Maybe we should add a description in the README.md file. What do you think ?

You are right @guilbep, let me do it right now

**Review by charlottegiseleweil — APPROVED** [review]

**Comment by guilbep** [comment]
Bravo la team ! :) @EPFL-ENAC/enac-it4r

**Pull request merged**
